# This is a basic workflow to help you get started with Actions
name: Rahul

# Controls when the action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # latest checkout

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v4   # new stable version
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html
