name: Rahul

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - name: Run a one line script
        run:
          echo Hello World!

      - name: Run a multiLine scipt
        run:
          echo add other action to build!
          echo test,, and deploy your project.

